from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from app.database import get_db
from app.models.task import Task
from app.schemas.task import TaskCreate, TaskResponse

router = APIRouter(tags=["Tasks"])

# 🟢 Route to GET all tasks
@router.get("/tasks", response_model=List[TaskResponse])
def get_all_tasks(db: Session = Depends(get_db)):
    return db.query(Task).order_by(Task.created_at.desc()).all()

# 🟢 Route to POST a new task
@router.post("/tasks", response_model=TaskResponse)
def create_new_task(task: TaskCreate, db: Session = Depends(get_db)):
    # Convert the Pydantic schema into a SQLAlchemy model
    db_task = Task(
        title=task.title,
        description=task.description,
        operator_id=task.operator_id,
        startup_id=task.startup_id,
        status=task.status
    )
    
    db.add(db_task)
    db.commit()
    db.refresh(db_task) # Gets the new ID generated by MySQL
    return db_task
@router.patch("/tasks/{task_id}/status", response_model=TaskResponse)

def update_task_status(task_id: int, new_status: str, db: Session = Depends(get_db)):
    
    # 1. Look up the specific task in the database
    db_task = db.query(Task).filter(Task.id == task_id).first()
    
    if not db_task:
        raise HTTPException(status_code=404, detail="Task not found in ledger.")
        
    # 2. Update the status string
    db_task.status = new_status
    
    # 3. Save the change back to MySQL
    db.commit()
    db.refresh(db_task)
    
    return db_task